from setuptools import setup

setup(
    name="insec",
    version="0.0.1",
    url="https://github.com/eth-sri/code-completion-attack.git",
    author="Slobojan Jenko, Niels Mündler, Jingxuan He, Mark Vero, Martin Vechev",
    author_email="niels.muendler@inf.ethz.ch",
    description="Reproduction Package for \"Black-Box Adversarial Attacks on LLM-Based Code Completion\"",
    packages=["insec"],
    install_requires=[
        "transformers",
        "wandb",
        "lizard",
        "diff-match-patch",
        "omegaconf",
        "matplotlib",
        "bert_score",
        "tiktoken",
        "openai==0.28",
        "accelerate",
        "fire",
        "nodejs-bin",
        "tabulate",
        "jsonlines",
        "sentencepiece",
        "bitsandbytes",
        "mistral_common",
        "mistralai",
        "datasets",
        "fuzzywuzzy",
        "codebleu",
    ],
)
