_wandb:
    value:
        cli_version: 0.26.1
        e:
            eul3jpks7vs81xw3ffrmv6byvog1g235:
                args:
                    - --attack_tokenizer
                    - Qwen/Qwen3.5-4B
                    - --output_dir
                    - results/transfer2_qwen35
                    - --experiment_name
                    - transfer2_qwen35
                codePath: main_code/attack/Adversarial_attack/INSEC/main.py
                codePathLocal: main.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "3936290357248"
                        used: "3021412704256"
                email: jack90213@gmail.com
                executable: /home/jack/anaconda3/envs/Thesis/bin/python
                git:
                    commit: 02c6e8694a3adcf212c6c6c47f5fe0d83810177f
                    remote: https://github.com/sqoojack/Master-Thesis-CodeGuard.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-195dc047-c39f-ae87-57ab-7c61b49cdad9
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-6958e318-1d39-7e14-466d-a4e3b8e6558c
                host: HSNL
                memory:
                    total: "134551302144"
                os: Linux-6.8.0-110-generic-x86_64-with-glibc2.35
                program: /home/jack/Thesis_topic/main_code/attack/Adversarial_attack/INSEC/main.py
                python: CPython 3.12.12
                root: /home/jack/Thesis_topic/main_code/attack/Adversarial_attack/INSEC
                startedAt: "2026-05-08T10:14:28.972953Z"
                writerId: eul3jpks7vs81xw3ffrmv6byvog1g235
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.26.1
            "6": 5.8.0
            "12": 0.26.1
            "13": linux-x86_64
dataset:
    value: cwe-089_py
experiment_name:
    value: transfer2_qwen35
model_dir:
    value: bigcode/starcoderbase-3b
output_dir:
    value: results/transfer2_qwen35
